#!/bin/bash 

if [ "$#" -ne 1 ] 
then
    echo "Usage: ./debug <PORT>"
    echo "Example: ./debug 5005"
    exit 1
fi

PORT="$1"

#rm -rf build ./proactive-iam-api/build
#gradle clean
gradle -Dorg.gradle.jvmargs="-Xdebug -Xrunjdwp:transport=dt_socket,address=$PORT,server=y,suspend=n" jettyRunWar

